version: '3.8'

services:
  postgres:
    image: postgres
    container_name: psych-postgres
    restart: always
    environment:
      POSTGRES_DB: psych_center
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: