spring:
  application:
    name: psych-center-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/psych_center
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysupersecretkey2345678901234567890802504735849759832478585858585